# Generated by Django 3.0.5 on 2020-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='título')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('ended', models.BooleanField(default=False, verbose_name='finalizado')),
                ('ended_in', models.DateField(blank=True, null=True, verbose_name='finalizou em')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
