# Generated by Django 3.0.5 on 2020-04-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='ended'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ended_in',
            field=models.DateField(blank=True, null=True, verbose_name='ended in'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
    ]
