env:
  global:
    secure: GnPibizRVB3gWmgroNkVqITDOYQN3/YyzgMHk1mNwcnxlTP8YWswvk2JEUiujBSlwuUPIFPVTMCOA7pQPEinVx8g/e/pezgx55OQfR7w5tkTXZ07eRd1PUBDqITSeD6+IWmMOBAtAU8dZF1Oz+vCZXHjoVNUUGfwtYlSr4ZeZxoHZJePt4U+RIjAVG6eXA+l0taRPCUmtdwB4Lv7GUjuYk0JdL2uzMgOrRsJm78WvBQY6xGNvdFqcgibesAxKrEzTrgR06eY+nQYrRYkI2xVWCfOIeWngNQFcfRklAuHwtj361erdak/63mKcBrsXfFbs18/iIkmP9hJqhyfL1u1BA4GPjPFADNewheYMrXFBbPGHG9lyZieUDL15oM80wLP8n3lexV5bL9LUQxtDQmZncxRI3DO91P9AXOKrUPuLrAmqIsmvEGz1jHg0YdtZY2UlZHu3J7CBtt10CUSRtBkwb15QfUT0AkFd3GVtClp9N+Keq64h+2/16s+deUmZXSHXMgR58oRS7gxhw+th8uo+FfR9O/XnftwI4CfZsJSxyAkDBWWq6OVQbYsQLGn3oXv/j9jItjuN6S7JLaJ43SMo0KP0+IgeOYA0vd+tSYtLx7F7Nd1onCUtaAaAEPDfF96suAXDP8NPMvj5Gzap+5o+qfm4hXNjLSFswPDxfN3Viw=
language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python manage.py test
