dist: xenial
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: PzkevF3N+MbABpogxcmxXsRANeZQUA6yhfxIwVr+PmecuMBV0wIxMC2arfLBBag5dlBZ3JYcBF7AvgDQlV0unUGnug0+gsXWDnv7gq5h2ZUK2vaPgnTB2LvVWVh4MEcQR+QycrHAfFqmlgKATk9lY7w30OxPZEzFTKaHmUIRecTiB/rTHd/qjUjfboqubA0dm79KPGt2apsuQXn23RayrskV7Xue4xQXFB72wMroNMUQqD2OXyDjpSKy7A57E2WeAeMGBVC5HRBbEk2UzUdXCA71G/RkOZJMH0Igs2VT+KzioEObjJycS1mB3kGZgTmhBSiBsDWK3UOUH96d2wg1jDH9nZbs/CVD/V+aVlg+mt6I3uQBKPXmHp8XX6w20uT/VRwTgdNvA34Yv8xnsfc4GRyvHwY8QdJoC6F9J6rClcvHciViZSHcdXYxMUUo2bFJia5Bty/XSKu+7DR4/G/SqDdvHGYvzF23UFIysKF3s6e46+OgHdgZ49qrkjOc+N243nCpASLASe9TRruSgX+tcqUcoq4Z6S7Z9aEjwGzrtb7neCVBGW/6NKfD5iGvvXiEHrGNA5ZcjUBejlwFn+hZUv7Fui+ciVhV8kP9MZ2IBr63GUKoFc/nLTgAM4CdNBuwa8dSuWXQlD49QwL0ZFdzCignMjyuZRsrbadwQCNbucs=
  app: carlos-moreno-to-do
  on:
    repo: carlos-moreno/to-do-list
