dist: xenial
env:
  global:
    secure: LrCveNVe58BlH9AbvideV+mgwc+Cw5Vh6XpnG5vxt5dBmWsL1AycjVUyUzRvT1Mrbwzx6dYO/oxblnwQD9M/jcMwg6x6RrfShVv1ab4iLxP78H7cxgUUQ9T8qr/kfEcushMvNoblNPdcpSS6YrPcM41SwZg9PhVmdj/tHQrBeFlJ+ZzXNlZ7yDIhqXeJTkPKIiqFlSWPTQxJ+MLeWLiY2CbbgeXwlnRS4enPtea3Wmbiz/NkuD6vQa9lcvVCIkQAkcUL/upZw0RXoVkPL64cJBWHDS5Y3PIQmMTuc5iT2dHRhV01NKcVZeLmQtLMQlJQO+AgJAo19khoawFlH86XvFE044/9UR2nygmNGOposOx2qn4LvwZKbyN9LGR4uXDpLJGfNkJZIr8me7lAeZWr48M/+F1N7sDA119dvDGBcgApMXF5/YzYINiUwDCYTxib8Z9V2REwlVzlcONk99PDrWTkLjnZev4ldxgO9EKNtIjMFKk9gphREhWH/LikaiheAORAhpK03JDWgROE+JXIGAIsLRmSsICkrQM0/q3ba81uIuS6LTqka8OEzRECna6AWChmWNy55SF3Vh+Hwopw/xsNdMTrGTmm/WYtqXh/8/pChExt8jwIUVj4d7Mj+5orfIYpuPL41IUpj2vvSzmTj7FGvxFxg4dHr5bTU1+Xx20=
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: carlos-moreno-to-do
