dist: xenial
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: aEV1ogkkKVlNBJJOd/udsx+4CyNlBGbt6YogH4VUFtqE4aDPbe2++C9S3rXcp7oWLG3JrDaw+3F64aMneSMpCJCPIoLyH5/IanD2dX2tmVYbM4x50eahCdO0d+q04wMTvc3bV/h56IUwcmQApTabdPIq87PsGuknao904XsgHwnrnDAObcSVXhyTMP9AVH87WXMqEmPwm0DSY7duQVeAHwJzYogcJPIMtOF1w5NgBvbduDcXrHFKDiAxKLqnu+VB01REJ5TB2WmTJw0xjgBhwlwMrkzw0uNo494Q5y/nlkb+OFPufD7pPPJAiQROU7gPlahuuh7NqswIbw2rWlB8+vxHxs51MgA5wv0LigTXONxZ1t6ZTwed7g1r8vZL8V7aEXJYUrPteKnvKXAwr5nSbzGO6yzwV7w7zK/X6X6C6rb5IUV2y8DrTT0bp6ZViguQsekGFI0SLPDHkWYrInGeYMchUDH8Uz88BpZMxT+B78lK9LJj5hjWflT1wz5gXsva5k8N2L6fCs2P/Ol1NfSqXDRQCnkla28z2QaCcQf3tBKpcnRkUL3s7oozRN+RvX3sQiiDWRH9LMWtmJSKZlRUbPAsZrhdRVKZj1OajpGA7s+vBTYt+IQ6VE951C3cn0vZFhvYImQD2dtf4nF14o/8kCuHjABf9+VG8uHwz9/oUpg=
  app: carlos-moreno-to-do
  on:
    repo: carlos-moreno/to-do-list
