dist: xenial
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: carlos-moreno-to-do
env:
  global:
    secure: g2plh6t4OmAZSk9wLUjbIA9bjJmGrvOVOnwQV78WafOwj31AvwTrkTxMGA/e3elbqTwDC8VI5gWE1vbB6XA8YU1OrP/eJj4HqATPPCe/GZU8zNOwJ+6yf2jrk/RAIg95l6xOrPrsv09WHCEwRnkoBSvdrqTt6KpUxJWGL/s/TPaJuJnLFlYaIPnRIstEucHZJpyxvB40/zvMtAbxXoPgdS8VYM5xewyoM/BD77E6rmqs26xUhvMLthrMvF2Ci69ga6bxkx93T/qkqjeetka2HaQ2aD/kMkc5fpcPyk9cPhDm4SocbmwGe1z0GBeY1IkX5BCa1d57qJAjjD72/HbvbEcPw42XxlK0Scb8J38BJRgsvDrbAkY1IvmwDXwP6bKAsfsdjK8WZ0RdaFkCrsQb3aNO+dM0YxB+0T8fXqCa6uzXvRz8YMHoim+MILgINOy+QtTu/it4Qm3geZk02tESX9hTs8q+IxIQ4FNNWpVzkRNXMZCApRs9JrfmAetOvlyNg43fDGfmgb0tIcFILlMVWuF7c1d/WmbySrLDt+0KQ0kfWYZMeVUUg2Yx+xoRXfSyiEG1ZeoT7cu+3uTnUc93bPdED3VFA3CiDp1HrdOSmJRXSqN/u16FcNOa84fMYmB+f1/lSmRSIGxaNkAS1iDXJjQGG7Yp0VQki9IBduXiyyQ=
