dist: xenial
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: WKEQujbKXmPjsDjVi2SzFP0Me5PFFUOjj1WeY3N9o+pYRzG5z+wS+D2XqyMJEvIuCGqde505khPVPrNTcVW3BUzCtn9nIv6/1z922nus3q9vl93R9W87hVKCyi7k0fOE6KTB4JXVmqnQhZh3wtaB7TDjkL6gmG7618y0w3ygAHnMOQ/179KKiXhzBM4ksgqFxAD8bT4+LCGf6MXl5i7tzBDeYSyL06bzyJXbkcH83hIpDDdMlAV/LaYj5+S2sMqYNSJPLGsO6+cMdAadsWzQ3PpE83HVy4jpbLWRlRu8dk4tHXxUVeeMdOQIXL2XB19VKkPWUWwS1FhCCurjbalhU0NZXenPV4Ua0F8aAcuT86Y4TidCy09qbrpIsuFaiYQ0UyIPfqoDL+nMnqqI68SFzT7WSj7kMjjCzPAuCYjbwRSp9SeMsQnhuE5GYtPArqxTQE7ft3ysqDi9rAFeyRFPSAwShkOMact/o4tqzVSUWYqZzxAoz2EhvOX9C0at/OU+jZ64M/gycgetgwGtTpNJotIqe51uZ/30v+8RELWvGSHnWAYWNmPiWdgpNSQjfE9ZSdpdEexYOAWVoiEVw69+5uZbEatB6PReRq/eca91fXLnDIHYWcw/rGmRNZqN/AkQM52F005MiUulYtEMhp/QytwhX9o5lms9HilccLeJQVQ=
  app: carlos-moreno-to-do
  on:
    repo: carlos-moreno/to-do-list
