dist: xenial
env:
  global:
  - secure: iG5TsOmOfwNJ0qQ13Y/fZGgNy6/zX9Lp2D6YQss+6c/MJZeCQ/dXmWDIu2R/AY/FgSNQHp7mF/DzRM++q18SG7QQAwsakZVxL32OEP8YBr31wpeW68Mpdto/h/N/lfzN5JdLfYwMNqVE12cJlP+wPLrTFT062a+qogSH9q7SeMELekEcm8QaW/ijA4YCUmyNPcjA5zn5yaiZpTE8+3QMI/yqfn8So4tjIyRBmb+mLdTxZaKOXxJFjwlc953UE83h5CWY6Np0BdLwUc6mZTzsEZyk6UBMBw4WA7guICbTzQRMZNu0ZRBCurO6Y6HRPoKwY0bfrgHLWUC30WEtLapuq4SAMzapokAS5uMAPUY0oy0L7/xhfW2wQddSk8eAyEZFDfNCgifpOwDPHJdQkhKvqvN3khYAhLR7CMCMFbC8seicJKYH4UfWQRyvcA9niLMYS/tL1ZmPtSXOFzrt54Jhdh2dYsnZH1I/IXcFo/7gq3QfWPIuejGqlZ/hr75hkKgvv0/LAGp0fsK5AiPlX2KAkJl7sZuoIZr/VDnAY/zJv/M8nQog4YbNqwNseLomPtdaG9uRILT099XkfgcnI1Q8HMS3VVrRFDb9MYt7bG/s84AKVl4ZbL1HyC87GYDhCk01j1yP0fg1u87LHlDKNAbxBUpKh+0QbRXe2thyEzhR6kg=
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: carlos-moreno-to-do
