dist: xenial
env:
  global:
    secure: SvVsPXzlSwHxgZZaqFxyyL43WPuZnij6IcD6FTyNvGW92KR5F9OPGKC3cKAy+WE2+nyM/e93Kpcy/p8RZ4BISCp0Pzo6Ol1nmr2YyIu77I+2DBKghTliKE17Gwz/HbQJ8Mt1x5VVDlY3F2h45TviG+OtJAVNHu+Bw2+yvEjV3ASL39jXaDhy1C2dmTdUiDgFh2iu8Dal0Odc55ZXf2BbySS5SQRds18EpgsiypZLZbbfJrs/QqJNFgYIRw/Ods4cdhO0u+R2XrfHD57ndKi2fXLVy2D8UfrVp3y5+QKo/caffAXZ21UfZ4SgwMHx3+TWZxHb/ZYL7sSaIFpcIj/mLc6XSc341oQlrJKio51qyDqC9H81Ome5VwWq94ypMY51CUqFngAL6jYChkki49PukiHujfHyVkpGgPFrVnbr2ZCMh3zhO1mD1/ZOWUNGarwOpEYJEKGBOf/gbn51ttgAsoL+zDb7SfnNd1G+koYX32mlDFnGKwOe1aMjcFhB9shV6S5ft5fsVIHukUzMAFgwk/NZ9sUNCW3/k4er+WXsOOYbbScvR/igMXaM7Xq4N+CX+2hB2u//8JWjP2JUiJRwjgkb1iglcppfIr91tmc20iIo3IYvTyaTKL4FM3NyO/amz2wI2pznQ3FrHyUeOmKasfyfXTpqi8E74ByxUjtD4nE=
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: carlos-moreno-to-do
