dist: xenial
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: QPTerubuqYi6fWabCqiO1KxTXRpkCJtnrPJdZNuVd3EcPkPgpoMErzJVeF1DxKlraezrlbFb27Y7AkcBFkTLqAAX9f8ELMx2Rz1fO/wJaPXlnreID0OGBhnKDzkjZiwBdfZiMNFvWJzqB1sFABzi/ptyuf5gf589gQ8V5UIeTMtTThhwvSIJ6KtbAKFB8OBYf1yGv0OxxGjwcfoogMtrUFnoaRwXwB1JgcNRG5V9CRJOVvHiqKCG1AxzYspxsJMHIgYDymTiOuY04zgwfCRgQ/LntvIyVy/uJlKgFA6WlmPZ2UrAlUbojc+yLfIHfi1evIucWMBJUx3AxBVQQPbbrE/46RMvFK6f7ZdUyOBayCRqPLR9pU5QNs2pKwtUr3Co6wDd9B9QpwpdKCMTt3yTfBL1MzJiz4w4ctFG5TZC/5ASN6UkS+Gbx9R3eazfRuYcMHoMgH5rczBcxYV8avk0M1VBGoMxYVPb3MqeLas35kYKzEKW2cwB69Vwx6KHH37LUr4zKiq/XRkgxRGIQexcbxPCy5c7ZFpR/KQ/V2DSdlCwjWhZYhbrjUBaHk1b9fuxQcCJyjxmUWzWkrQCyGNPBfvMqo1ly9jJ1+xslz8k6Q2/kM0bFlTSlDtxtAd4atUOAMWcCiNW18vrIUaJdJmEl2k/yuCLmhuHPxvikuI9Qng=
  app: carlos-moreno-to-do
  on:
    repo: carlos-moreno/to-do-list
