dist: xenial
env:
  global:
    secure: cotI5fZld2t9etkLjUA1sp3Hqaea5Lr5Ru6rUcQU+RfmlIXmOhpHFRWlrMTFC7cFfaCu/UIXqgHwFt99LZkaWNxAmUvUnW5Q6Wi/LWAefLgZUVI/5+fP3RV4b9dh2RXsYieXzKTWIZD1j6zMcbZgWsrtiF7DmVt1dmsIYtcZpV/+m0MkoZFZHmzPvPXhLtkcizZYk1E3uRrbeh24YNqKWW0m8R8BoAeqbCTaiHzbk0ATvRw0HuKPkZ6V7QJipz2VtpNajvinsFPYbHbXcykUiVTDmhhbBjmCtjrK9e2YJqQPyS0PXF3G8OR71C3eodHJTcQ6t56CB2ivwefaoWvJf3WBEdV5DyG/9OfPOrCsWbjP4oIGgLfw9rYJebuEmd69kw2FrK1Kl6EHvwqrFpT0hmFSCRP1fSb3/q3LCESTYZSK0Q1loPYPXN+58yTeMQCFSQcouP9NWK+TV5gFwnVCYGRIj2UnMKhLC6FTZQZvynwh27/I47EcZkjEfK15b2Mvx8Jz6NNAE+QUL68rl3XtU2rwfjKFEgz55zMGxNlBnGTRkLamwj1MrlITnmZ+P70y7F65f/+2hEfLG6uXtQ0Zy101SosyMtUT2clTsuI9efpX3cFNdg1nPHCE8ecAny4frj+OPZMi0xisRJbng+4yFLbX6nPtpHDOJrTVs1gFVtY=
language: python
python:
- '3.8'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: HEROKU_API_KEY
  app: carlos-moreno-to-do
  on:
    repo: carlos-moreno/to-do-list
