dist: xenial
language: python
python:
  - '3.8'
install:
  - cp contrib/env-sample .env
  - pip install -r requirements.txt
script:
  - python manage.py collectstatic --noinput
  - python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: rLthCO0acS1dO4cDlHCu200TTdt6arYOJxl3CZloSa283t97elZD6WuOiqkDZf38RXR1VHNl69joFZSgpVV6tWgjuuZihFvhJy95LpongPknk+1y38V9Q0WAspNIQ493+YD6/yo+v7v60Sn+L9DDfTl/TuPT6FnkXLx5eXy3JOxGxHKlV5Xa8CnL9DF2FHtxo6JJI/bLPtib05t7/dL9Pvxkvikqnf3eMvUOKiiQL4GuFveKj+HJsRg4gUrABUqHq/kO0uDg1S/3HkI+IkGhSQ62LkKY/kkDzcPMbkf+R2ylRMVLUVzgpGCdJ0ByBIfj2Nk83tvmiO/xgGnx+lXuJRi30U+pYQDC2Y8RcqDeHtANMGhvehPsyYBV9MKzULAv+67hyg+6l2Xi/+gARDkuQ26InP11n1Ff04bnV+9j6L8Qe669Y9cUQcbIblALe6+fw+Bg3QgV2rk1GLjISwxFi3FnA0F1c8iIMya+GtDLSFcd961pQm606Z/4m8GO171nsxy44wd3Ta1PoJDAAEx0aDevsjz/QtC+jA+KKw+ViUXWiHdMoMaktlYN0FrB3Yn/+fk+AwYvy60URH8cktI9FWf+C62I5fHqGmT/3M2ciQ+ChvAd2OHCkq7CQpR1uZLCjoy8kMX+zUwWDQk2QPZgcvTkgeDuodOqQQHWkO1Zq0k=
  app: carlos-moreno-to-do
  on:
    repo: carlos-moreno/to-do-list
